# Generated by Django 4.0 on 2022-01-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maketodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
