# Generated by Django 4.0 on 2022-01-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maketodo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todocreator',
            new_name='user',
        ),
    ]
